#!/bin/env python3

import wfipclib as wi
import wftest as wt
import time

# Give wayfire time to start
time.sleep(1)

try:
    socket = wi.open_socket()
    if wi.ping(socket):
        wt.ok()
    else:
        wt.wa()
except SystemExit:
    raise
except:
    wt.crash()
